nelmio_cors:
    defaults:
        allow_origin: ['https://www.meydetour.com', 'http://localhost:5173']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/':  # Apply the CORS settings to all routes
            allow_origin: ['https://www.meydetour.com', 'http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600
            allow_credentials: true
