nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://www.meydetour.com']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: [ 'https://www.meydetour.com' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'GET', 'POST', 'OPTIONS', 'PUT', 'DELETE' ]
            max_age: 3600
            allow_credentials: true
